name: image-conversion-linux-test-env

services:
  laravel:
    container_name: image-conversion-laravel
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../laravel:/workspace:cached
      - image-conversion-node_modules:/workspace/node_modules
      - image-conversion-vendor:/workspace/vendor
    tty: true
    ports:
      - 5173:5173

volumes:
  image-conversion-node_modules:
  image-conversion-vendor: